stages:
  data_ingestion:
    cmd: python src/textSummarizer/pipeline/stage_01_data_ingestion.py
    deps:
      - src/textSummarizer/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/samsum_dataset

  data_validation:
    cmd: python src/textSummarizer/pipeline/stage_02_data_validation.py
    deps:
      - src/textSummarizer/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/samsum_dataset
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/textSummarizer/pipeline/stage_03_data_transformation.py
    deps:
      - src/textSummarizer/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_validation/status.txt
    outs:
      - artifacts/data_transformation/samsum_dataset

  model_trainer:
    cmd: python src/textSummarizer/pipeline/stage_04_model_trainer.py
    deps:
      - src/textSummarizer/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - artifacts/data_transformation/samsum_dataset
    params:
      - TrainingArguments.num_train_epochs
      - TrainingArguments.warmup_steps
      - TrainingArguments.per_device_train_batch_size
      - TrainingArguments.weight_decay
      - TrainingArguments.logging_steps
      - TrainingArguments.evaluation_strategy
      - TrainingArguments.eval_steps
      - TrainingArguments.save_steps
      - TrainingArguments.gradient_accumulation_steps
    outs:
      - artifacts/model_trainer/pegasus-samsum-model
      - artifacts/model_trainer/tokenizer
